import { MeasurementDto } from "./components/measurement-item/measurementDto";

export const MEASUREMENTS: MeasurementDto[] = [
    {
        id: 1,
        userId: 23,
        measurementDate: new Date(2022, 0, 2),
        weight: 73,
        waist: 90,
        neck: 38,
        chest: 100,
        hips: 25,
        biceps: 37,
        tigh: 45,
        calf: 23,
        fat: 15,
    },
    {
        id: 2,
        userId: 23,
        measurementDate: new Date('2022-01-03'),
        weight: 72,
        waist: 90,
        neck: 38,
        chest: 100,
        hips: 25,
        biceps: 37,
        tigh: 45,
        calf: 23,
        fat: 14,
    },
    {
        id: 3,
        userId: 23,
        measurementDate: new Date('2022-01-04'),
        weight: 71,
        waist: 90,
        neck: 38,
        chest: 100,
        hips: 25,
        biceps: 37,
        tigh: 45,
        calf: 23,
        fat: 13,
    },
    {
        id: 4,
        userId: 23,
        measurementDate: new Date('2022-01-05'),
        weight: 70,
        waist: 90,
        neck: 38,
        chest: 100,
        hips: 25,
        biceps: 37,
        tigh: 45,
        calf: 23,
        fat: 11,
    }
];