
-- ADD ACTIVITY TYPE TABLE
CREATE TABLE [dbo].[ActivityTypes](

			[Id] [bigint] IDENTITY(1,1) NOT NULL,	

			[Name] [nvarchar] (100) NOT NULL,

			[Description] [nvarchar] (300) NULL,
	
			[MET] [float] NOT NULL,
	
CONSTRAINT [PK_dbo.ActivityTypes] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]