
-- SEED ACTIVITY TYPE TABLE

INSERT INTO [dbo].[ActivityTypes] ([Name], [Description], [MET])
VALUES
('Bicycling 1',	'mountain, uphill, vigorous',	14),
('Bicycling 2',	'mountain, competitive, racing',	16),
('Bicycling 3',	'BMX',	8.5),
('Bicycling 4',	'mountain, general',	8.5),
('Bicycling 5',	'<10 mph, leisure, to work or for pleasure',	4),
('Bicycling 6',	'to/from work, self selected pace',	6.8),
('Bicycling 7',	'on dirt or farm road, moderate pace',	5.8),
('Bicycling 8',	NULL,	7.5),
('Bicycling 9',	'leisure, 8.9 km/h (5.5 mph)',	3.5),
('Bicycling 10',	'leisure, 15.1 km/h (9.4 mph)',	5.8),
('Bicycling 11',	'16-19.1 km/h (10-11.9 mph), leisure, slow, light effort',	6.8),
('Bicycling 12',	'19.2-22.4 km/h (12-13.9 mph), leisure, moderate effort',	8),
('Bicycling 13',	'22.5-15.6 km/h (14-15.9 mph), racing or leisure, fast, vigorous effort',	10),
('Bicycling 14',	'15.7-30.6 km/h (16-19 mph), racing/not drafting or > 19 mph drafting, very fast, racing general',	12),
('Bicycling 15',	'>32 km/h (>20 mph), racing, not drafting',	15.8),
('Bicycling 16',	'19.2 km/h (12 mph), seated, hands on brake hoods or bar drops, 80 rpm',	8.5),
('Bicycling 17',	'19.2 km/h (12 mph), standing, hands on brake hoods, 60 rpm',	9),
('Bicycling 18',	'unicycling',	5),
('Calisthenics 1',	'push ups, sit ups, pull-ups, jumping jacks, vigorous effort',	8),
('Calisthenics 2',	'e.g., push ups, sit ups, pull-ups, lunges, moderate effort',	3.8),
('Calisthenics 3',	'situps, abdominal crunches, light effort',	2.8),
('Calisthenics 4',	'light or moderate effort, general (e.g., back exercises), going up & down from floor ( 150)',	3.5),
('Circuit training 1',	'moderate effort',	4.3),
('Circuit training 2',	'including kettlebells, some aerobic movement with minimal rest, general, vigorous intensity',	8),
('Stair-treadmill',	NULL,	9),
('Rope skipping',	NULL,	12.3),
('Rowing 1',	'stationary ergometer, general, vigorous effort',	6),
('Rowing 2',	'stationary, general, moderate effort',	4.8),
('Rowing 3',	'stationary, 100 watts, moderate effort',	7),
('Rowing 4',	'stationary, 150 watts, vigorous effort',	8.5),
('Rowing 5',	'stationary, 200 watts, very vigorous effort',	12),
('Pilates',	NULL,	3),
('Yoga Hatha',	NULL,	2.5),
('Yoga Power',	NULL,	4),
('Yoga Nadisodhana',	NULL,	2),
('Yoga Surya Namaskar',	NULL,	3.3),
('Ballet 1',	'modern, or jazz, general, rehearsal or class',	5),
('Ballet 2',	'modern, or jazz, performance, vigorous effort',	6.8),
('Tap',	NULL,	4.8),
('Aerobic, general',	NULL,	7.3),
('Dancing 1',	'ethnic or cultural (e.g., Greek, Middle Eastern, hula, salsa, merengue, bamba y plena, flamenco, belly, and swing)',	4.5),
('Dancing 2',	'ballroom, fast',	5.5),
('Dancing 3',	'general dancing (e.g., disco, folk, Irish step dancing, line dancing, polka, contra, country)',	7.8),
('Dancing 4',	'ballroom dancing, competitive, general',	11.3),
('Dancing 5',	'ballroom, slow (e.g., waltz, foxtrot, slow dancing, samba, tango, 19th century dance, mambo, cha cha)',	3),
('Running 2',	'6.4 km/h (4 mph)',	6),
('Running 3',	'8 km/h (5 mph)',	8.3),
('Running 4',	'8.4 km/h (5.2 mph)',	9),
('Running 5',	'9.7 km/h (6 mph)',	9.8),
('Running 6',	'10.8 km/h (6.7 mph)',	10.5),
('Running 7',	'11.3 km/h (7 mph)',	11),
('Running 8',	'12 km/h (7.5 mph)',	11.5),
('Running 9',	'12.9 km/h (8 mph)',	11.8),
('Running 10',	'13.9 km/h (8.6 mph)',	12.3),
('Running 11',	'14.5 km/h (9 mph)',	12.8),
('Running 12',	'16.1 km/h (10 mph)',	14.5),
('Running 13',	'17.7 km/h (11 mph)',	16),
('Running 14',	'19.2 km/h (12 mph)',	19),
('Running 15',	'20.9 km/h (13 mph)',	19.8),
('Running 16',	'22.5 km/h (14 mph)',	23),
('Running 17',	'cross country',	9),
('Running 1',	'running',	8),
('Running 18',	'stairs, up',	15),
('Running 19',	'on a track, team practice',	10),
('Running 20',	'training, pushing a wheelchair or baby carrier',	8),
('Running 21',	'marathon',	13.3),
('Badminton 1',	'competitive',	7),
('Badminton 2',	'social singles and doubles, general',	5.5),
('Basketball 1',	'game',	8),
('Basketball 2',	'non-game',	6),
('Basketball 3',	'basketball, shooting baskets',	4.5),
('Basketball 4',	'basketball, drills, practice',	9.3),
('Basketball 5',	'basketball, wheelchair',	7.8),
('Billiards',	NULL,	2.5),
('Bowling',	NULL,	3.8),
('Boxing 1',	'in ring',	12.8),
('Boxing 2',	'punching bag',	5.5),
('Boxing 3',	'sparring',	7.8),
('Broomball',	NULL,	7),
('Cheerleading',	'gymnastic moves, competitive',	6),
('Coaching 1',	'football, soccer, basketball, baseball, swimming, etc.',	4),
('Coaching 2',	'actively playing sport with players',	8),
('Cricket, batting, fielding',	NULL,	4.8),
('Croquet',	NULL,	3.3),
('Curling',	NULL,	4),
('Fencing',	NULL,	6),
('Football 1',	'competitive',	8),
('Football 2',	'touch, flag',	8),
('Football 3',	'touch, flag, light effort',	4),
('Football 4',	'football or baseball, playing catch',	2.5),
('Frisbee 1',	'playing, general',	3),
('Frisbee 2',	'frisbee, ultimate',	8),
('Golf 1',	NULL,	4.8),
('Golf 2',	'walking, carrying clubs',	4.3),
('Golf 3',	'miniature, driving range',	3),
('Golf 4',	'walking, pulling clubs',	5.3),
('Golf 5',	'using power cart',	3.5),
('Gymnastics',	NULL,	3.8),
('Hacky sack',	NULL,	4),
('Handball',	'handball, team',	8),
('High ropes course',	'multiple elements',	4),
('Hang gliding',	NULL,	3.5),
('Hockey',	NULL,	9),
('Horseback riding 1',	NULL,	5.5),
('Horseback riding 2',	'trotting',	5.8),
('Horseback riding 3',	'canter or gallop',	7.3),
('Horseback riding 4',	'walking',	3.8),
('Horseback riding 5',	'jumping',	9),
('Jai alai',	NULL,	12),
('Martial arts 1',	'different types, slower pace, novice performers, practice',	5.3),
('Martial arts 2',	'different types, moderate pace',	10.3),
('Juggling',	NULL,	4),
('Lacrosse',	NULL,	8),
('Moto-cross',	'off-road motor sports, all-terrain vehicle, general',	4),
('Orienteering',	NULL,	9),
('Polo',	'on horseback',	8),
('Racquetball 1',	'competitive',	10),
('Racquetball 2',	'general',	7),
('Rock climbing',	NULL,	8),
('Rope jumping 1',	'fast pace, 120-160 skips/min',	12.3),
('Rope jumping 2',	'moderate pace, 100-120 skips/min, general, 2 foot skip, plain bounce',	11.8),
('Rope jumping 3',	'slow pace, < 100 skips/min, 2 foot skip, rhythm bounce',	8.8),
('Rugby 1',	'union, team, competitive',	8.3),
('Rugby 2',	'touch, non-competitive',	6.3),
('Shuffleboard',	NULL,	3),
('Skateboarding 1',	'moderate effort',	5),
('Skateboarding 2',	'competitive, vigorous effort',	6),
('Skating',	NULL,	7),
('Rollerblading 1',	'in-line skating, 14.4 km/h (9.0 mph), recreational pace',	7.5),
('Rollerblading 2',	'in-line skating, 17.7 km/h (11.0 mph), moderate pace, exercise training',	9.8),
('Rollerblading 3',	'in-line skating, 21.0 to 21.7 km/h (13.0 to 13.6 mph), fast pace, exercise training',	12.3),
('Rollerblading 4',	'in-line skating, 24.0 km/h (15.0 mph), maximal effort',	14),
('Skydiving',	'also base jumping, bungee jumping',	3.5),
('Soccer 1',	'competitive',	10),
('Soccer 2',	'casual',	7),
('Softball 1',	'or baseball, fast or slow pitch, general',	5),
('Softball 2',	'practice',	4),
('Softball 3',	'officiating',	4),
('Softball 4',	'pitching',	6),
('Squash 1',	'competitive, vigorous effort',	12),
('Squash 2',	NULL,	7.3),
('Table tennis',	NULL,	4),
('Tai chi 1',	'qi gong, general',	3),
('Tai chi 2',	'tai chi, qi gong, sitting, light effort',	1.5),
('Tennis 1',	NULL,	7.3),
('Tennis 2',	'doubles',	6),
('Tennis 3',	'doubles',	4.5),
('Tennis 4',	'singles',	8),
('Tennis 5',	'hitting balls, non-game play, moderate effort',	5),
('Trampoline 1',	'recreational',	3.5),
('Trampoline 2',	'trampoline, competitive',	4.5),
('Volleyball 1',	NULL,	4),
('Volleyball 2',	'competitive, in gymnasium',	6),
('Volleyball 3',	'non-competitive, 6 – 9 member team, general',	3),
('Volleyball 4',	'beach, in sand',	8),
('Wrestling',	'one match = 5 minutes',	6),
('Wallyball',	NULL,	7),
('Track and field 1',	'shot, discus, hammer throw',	4),
('Track and field 2',	'high jump, long jump, triple jump, javelin, pole vault',	6),
('Track and field 3',	'steeplechase, hurdles',	10),
('Archery',	'non-hunting',	4.3),
('Badminton 1',	'competitive',	7),
('Badminton 2',	'social singles and doubles, general',	5.5),
('Canoeing 1',	'on camping trip',	4),
('Canoeing 2',	'harvesting wild rice, knocking rice off the stalks',	3.3),
('Canoeing 3',	'portaging',	7),
('Canoeing 4',	'rowing, 3.2-6.3 km/h (2.0-3.9 mph), light effort',	2.8),
('Canoeing 5',	'rowing, 6.4-9.5 km/h (4.0-5.9 mph), moderate effort',	5.8),
('Canoeing 6',	'rowing, kayaking, competition, >9.6 km/h (>6 mph), vigorous effort',	12.5),
('Canoeing 7',	'rowing, for pleasure, general',	3.5),
('Canoeing 8',	'rowing, in competition, or crew or sculling',	12),
('Diving',	'springboard or platform',	3),
('Kayaking',	'moderate effort',	5),
('Water skiing',	'or wakeboarding',	6),
('Jet skiing',	'driving, in water',	7),
('Skindiving 1',	'fast',	15.8),
('Skindiving 2',	'moderate',	11.8),
('Skindiving 3',	'scuba diving, general',	7),
('Snorkeling',	NULL,	5),
('Surfing 1',	'body or board, general',	3),
('Surfing 2',	'body or board, competitive',	5),
('Paddle boarding',	NULL,	6),
('Swimming laps 1',	'freestyle, fast, vigorous effort',	9.8),
('Swimming laps 2',	'freestyle, front crawl, slow, light or moderate effort',	5.8),
('Swimming 1',	'breaststroke, general, training or competition',	10.3),
('Swimming 2',	'breaststroke, recreational',	5.3),
('Swimming 3',	'butterfly, general',	13.8),
('Swimming 4',	'crawl, fast speed, ~69m (~75 yards) per minute, vigorous effort',	10),
('Swimming 5',	'crawl, medium speed, ~45 m (~50 yards) per minute, vigorous effort',	8.3),
('Swimming 6',	'lake, ocean, river',	6),
('Swimming 7',	'leisurely, not lap swimming, general',	6),
('Swimming 8',	'sidestroke, general',	7),
('Swimming 9',	'synchronized',	8),
('Swimming 10',	'treading water, fast, vigorous effort',	9.8),
('Swimming 11',	'treading water, moderate effort, general',	3.5),
('Water aerobics',	'or water calisthenics',	5.5),
('Water polo',	NULL,	10),
('Water volleyball',	NULL,	3),
('Water jogging',	NULL,	9.8),
('Water walking 1',	'light effort, slow pace',	2.5),
('Water walking 2',	'moderate effort, moderate pace',	4.5),
('Water walking 3',	'vigorous effort, brisk pace',	6.8),
('Windsurfing 1',	'not pumping for speed',	5),
('Windsurfing 2',	'or kitesurfing, crossing trial',	11),
('Windsurfing 3',	'competition, pumping for speed',	13.5),
('Ice skating 1',	'ice dancing',	14),
('Ice skating 2',	'14.5 km/h (9 mph) or less',	5.5),
('Ice skating 3',	NULL,	7),
('Ice skating 4',	'rapidly, more than 14.5 km/h (9 mph), not competitive',	9),
('Ice skating 5',	'speed, competitive',	13.3),
('Skiing 1',	NULL,	7),
('Skiing 2',	'cross country, 4 km/h (2.5 mph), slow or light effort, ski walking',	6.8),
('Skiing 3',	'cross country, 6.4-7.7 km/h (4.0-4.9 mph), moderate speed and effort, general',	9),
('Skiing 4',	'cross country, 7.8-12.7 km/h (5.0-7.9 mph), brisk speed, vigorous effort',	12.5),
('Skiing 5',	'cross country, >12.8 km/h (>8.0 mph), elite skier, racing',	15),
('Skiing 6',	'cross country, hard snow, uphill, maximum, snow mountaineering',	15.5),
('Skiing 7',	'cross-country, skating',	13.3),
('Skiing 8',	'cross-country, biathlon, skating technique',	13.5),
('Skiing 9',	'downhill, alpine or snowboarding, light effort, active time only',	4.3),
('Skiing 10',	'downhill, alpine or snowboarding, moderate effort, general, active time only',	5.3),
('Skiing 11',	'downhill, vigorous effort, racing',	8),
('Skiing 12',	'roller, elite racers',	12.5),
('Backpacking',	NULL,	7),
('Walking',	NULL,	3),
('Hiking 1',	'at a normal pace through fields and hillsides',	5.3),
('Hiking 2',	'hills w/4.5-10kg (10-20lb.) load',	7.3),
('Race walking',	NULL,	6.5),
('Fitness 1',	'moderate',	4),
('Fitness 2',	'vigorous effort',	7.2)

